@Api_HostAddress = http://localhost:5000

## Get branches by Id
GET {{Api_HostAddress}}/api/Branches/1
Accept: application/json
###

## Get branches ordered by name and address
GET {{Api_HostAddress}}/api/Branches?_order="name desc, address asc"
Accept: application/json
###

## Get branches by page and size
GET {{Api_HostAddress}}/api/Branches?_page=1&_size=10
Accept: application/json
###

## Get branches by page and size, page 2
GET {{Api_HostAddress}}/api/Branches?_page=2&_size=10
Accept: application/json
###

## Get branches filter by name
GET {{Api_HostAddress}}/api/Branches?name=*anch&_order="name desc"
Accept: application/json
###

## Get products by category
GET {{Api_HostAddress}}/api/Products/category/men's clothing?title=f*&_order="title"
Accept: application/json
###
